version: "3.9"
services:

  design-system:
    # image: registry.iho.co/shared_services/shared-libraries/design-system/dss:latest
    image: registry.iho.co/shared_services/shared-libraries/design-system/dss:v1.0.7
    hostname: design-system
    environment:
      TZ: $TZ
    # volumes:
    #   - ./SignalRServer/Program.cs:/app/Program.cs
    #   - ./SignalRServer/:/app
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      update_config:
        delay: 10s
    networks:
      - apigateway

networks:
  apigateway:
    driver: overlay
    external: true
