- name: pull images
  hosts: '{{ HOST_NAME }}'
  connection: ssh
  user: bot
  tasks:
   - name: check path
     debug:
      msg: "CI_PROJECT_PATH : '{{ CI_PROJECT_PATH }}' , CI_COMMIT_BRANCH : '{{ CI_COMMIT_BRANCH }}'"

   - name: Delete content & directory
     file:
      state: absent
      path: '${HOME}/temp/{{ CI_PROJECT_PATH }}/{{ CI_COMMIT_BRANCH }}'

   - name: Create tmp directory if it does not exist
     file:
      path: '${HOME}/temp/{{ CI_PROJECT_PATH }}/{{ CI_COMMIT_BRANCH }}'
      state: directory

   - name: copy config
     become: true
     copy:
      # src: "{{ CI_PROJECT_DIR }}/{{ CI_CONFIG_YAML }}"
      src: '{{ CI_PROJECT_DIR }}/devops'
      dest: '${HOME}/temp/{{ CI_PROJECT_PATH }}/{{ CI_COMMIT_BRANCH }}'

   - name: create .env file
     copy:
      dest: '${HOME}/temp/{{ CI_PROJECT_PATH }}/{{ CI_COMMIT_BRANCH }}/devops/cd/.env'
      content: |
        TZ={{ TZ }}
        IHO_OTL_SERVICE_NAME={{ APP_ROUTE }}
        APP_ROUTE={{ APP_ROUTE }}
        APP_PORT={{ APP_PORT }}
        SUBDOMAIN={{ SUBDOMAIN }}
        CI_PROJECT_PATH={{ CI_PROJECT_PATH }}
        CI_COMMIT_BRANCH={{ CI_COMMIT_BRANCH }}

   - name: check config
     register: stackconfig
     environment:
      TZ: '{{ TZ }}'
      IMAGE: '{{ IMAGE }}'
      PROTOCOL: 'https'
      APP_ROUTE: '{{ APP_ROUTE }}'
      APP_PORT: '{{ APP_PORT }}'
      SUBDOMAIN: '{{ SUBDOMAIN }}'
      CI_PROJECT_PATH: '{{ CI_PROJECT_PATH }}'
      CI_COMMIT_BRANCH: '{{ CI_COMMIT_BRANCH }}'
     command: 'docker compose -f {{ CI_CONFIG_YAML }} config'
     # changed_when: False
     args:
      chdir: '${HOME}/temp/{{ CI_PROJECT_PATH }}/{{ CI_COMMIT_BRANCH }}/devops/cd'

   - name: Print yaml config
     debug:
      msg: "config : '{{ stackconfig.stdout }}'"

   - name: remove old deploy
     command: 'docker stack rm {{ STACK }}'
     changed_when: False

   - name: folder access permission
     command: 'chmod -R 777 ${HOME}/temp/{{ CI_PROJECT_PATH }}/{{ CI_COMMIT_BRANCH }}/devops/cd'
     changed_when: False

   - name: pull image
     register: pull_image
     command: 'docker pull {{ IMAGE }}'

   - name: Print pull image
     debug:
      msg: "pull image : '{{ pull_image.stdout }}'"

   - name: deploy
     register: stackdeploy
     environment: # داخل YAML نه BASH اجرا شده
      TZ: '{{ TZ }}'
      PROTOCOL: 'https'
      IMAGE: '{{ IMAGE }}'
      APP_ROUTE: '{{ APP_ROUTE }}'
      APP_PORT: '{{ APP_PORT }}'
      SUBDOMAIN: '{{ SUBDOMAIN }}'
      CI_PROJECT_PATH: '{{ CI_PROJECT_PATH }}'
      CI_COMMIT_BRANCH: '{{ CI_COMMIT_BRANCH }}'
     command: 'docker stack deploy -c {{ CI_CONFIG_YAML }} {{ STACK }}'
     args:
      chdir: '${HOME}/temp/{{ CI_PROJECT_PATH }}/{{ CI_COMMIT_BRANCH }}/devops/cd'

   - name: Print deploy config
     debug:
      msg: "config : '{{ stackdeploy.stdout }}'"
